name: Context Data
# run-name: "Manual Run by @${{ github.actor }}
on:
  workflow_dispatch:
jobs:
  GitHub_ContextData:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context Data
        run: echo "${{ toJson(github) }}"
      
      - name: Print Job Context Data
        run: echo "${{ toJson(job) }}"

      - name: Print Runner Context Data
        run: echo "${{ toJson(runner) }}"