name: Hello world Workflow
#on: [push] # Triggers the workflow on every push to the repository
on: [workflow_dispatch] # Triggers the workflow manually

jobs:
  say-hello: # Job Name
    runs-on: ubuntu-latest # Github hosted runners
    steps:
    - name: Greet the world
      run: echo "Hello World"